l1 = list(map(int, input("Enter List 1: ").split()))
l2 = list(map(int, input("Enter List 2: ").split()))
print("Same length:", len(l1) == len(l2))
print("Same sum:", sum(l1) == sum(l2))
print("Common values:", set(l1) & set(l2))
